[project]
name = "sdk-documentaation-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agentsdk-gemini-adapter>=0.1.0",
    "dotenv>=0.9.9",
    "openai-agents>=0.0.19",
    "rich>=14.1.0",
]
